version: '3.4'
services:
  react-nginx-app:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://localhost
        REACT_APP_MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    networks:
      - app-net
    expose: 
      - 80
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - spring-app
  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-net
      - db-net
    expose: 
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_STRAVA_REDIRECTURI=http://localhost/login/oauth2/code/strava
      - CLIENT_ID=${STRAVA_CLIENT_ID}
      - CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - MY_SUCCESSURL=http://localhost/
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-net
    expose: 
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
networks:
  db-net:
  app-net:
