server:
  port: ${PORT}

spring:
  application:
    name: effort-tracker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comchylb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
#    properties:
#      hibernate:
#        dialect:
#          storage_engine: innodb

  security:
    oauth2:
      client:
        registration:
          strava:
            provider: strava-provider
            client-id: 55684
            client-secret: ${SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/strava
            scope: activity:read_all
        provider:
          strava-provider:
            tokenUri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE